export const diseases = [
	{ label: 'Measles', value: 'Measles' },
	{ label: 'Mumps', value: 'Mumps' },
	{ label: 'Rubella', value: 'Rubella' },
	{ label: 'Polio', value: 'Polio' },
	{ label: 'Diphtheria', value: 'Diphtheria' },
	{ label: 'Tetanus', value: 'Tetanus' },
	{ label: 'Pertussis', value: 'Pertussis' },
	{ label: 'Hepatitis A', value: 'Hepatitis A' },
	{ label: 'Hepatitis B', value: 'Hepatitis B' },
	{ label: 'Human Papillomavirus (HPV)', value: 'HPV' },
	{ label: 'Varicella (Chickenpox)', value: 'Chickenpox' },
	{ label: 'Influenza (Flu)', value: 'Flu' },
	{ label: 'Pneumococcal Disease', value: 'Pneumococcal' },
	{ label: 'Meningococcal Disease', value: 'Meningococcal' },
	{ label: 'Haemophilus Influenzae Type B (Hib)', value: 'Hib' },
	{ label: 'Rotavirus', value: 'Rotavirus' },
	{ label: 'Tuberculosis (TB)', value: 'Tuberculosis' },
	{ label: 'Yellow Fever', value: 'Yellow Fever' },
	{ label: 'Rabies', value: 'Rabies' },
	{ label: 'Typhoid Fever', value: 'Typhoid' },
	{ label: 'Shingles', value: 'Shingles' },
	{ label: 'Cholera', value: 'Cholera' },
	{ label: 'Japanese Encephalitis', value: 'Japanese Encephalitis' },
	{ label: 'Zika Virus', value: 'Zika Virus' },
	{ label: 'Dengue Fever', value: 'Dengue' },
	{ label: 'Ebola', value: 'Ebola' },
	{ label: 'Malaria', value: 'Malaria' },
	{ label: 'Tick-Borne Encephalitis', value: 'Tick-Borne Encephalitis' },
	{ label: 'Leprosy', value: 'Leprosy' },
	{ label: 'Chikungunya', value: 'Chikungunya' },
	{ label: 'Avian Influenza (Bird Flu)', value: 'Bird Flu' },
	{ label: 'Hantavirus', value: 'Hantavirus' },
	{ label: 'Cytomegalovirus (CMV)', value: 'CMV' },
	{ label: 'Lassa Fever', value: 'Lassa Fever' },
	{ label: 'Middle East Respiratory Syndrome (MERS)', value: 'MERS' },
	{ label: 'Hepatitis C', value: 'Hepatitis C' },
	{ label: 'HIV/AIDS', value: 'HIV/AIDS' }
];

export const medications = [
	{ label: 'Immunosuppressants', value: 'Immunosuppressants' },
	{ label: 'Steroids (e.g., Prednisone)', value: 'Steroids' },
	{ label: 'Chemotherapy Drugs', value: 'Chemotherapy' },
	{ label: 'Antiretrovirals (HIV Treatment)', value: 'Antiretrovirals' },
	{ label: 'Anti-rejection Drugs (Post-transplant)', value: 'Anti-rejection Drugs' },
	{ label: 'Antibiotics', value: 'Antibiotics' },
	{ label: 'Antifungals', value: 'Antifungals' },
	{ label: 'Antivirals', value: 'Antivirals' },
	{ label: 'Blood Thinners (e.g., Warfarin)', value: 'Blood Thinners' },
	{ label: 'Biologics (e.g., for rheumatoid arthritis)', value: 'Biologics' },
	{ label: 'Allergy Medications (e.g., Antihistamines)', value: 'Allergy Medications' },
	{ label: 'Anti-seizure Medications', value: 'Anti-seizure Medications' },
	{ label: 'Monoclonal Antibodies', value: 'Monoclonal Antibodies' },
	{ label: 'NSAIDs (e.g., Ibuprofen)', value: 'NSAIDs' },
	{ label: 'Pain Relievers (e.g., Acetaminophen)', value: 'Pain Relievers' }
];

export const occupations = [
	{ label: 'Healthcare Worker', value: 'Healthcare Worker' },
	{ label: 'Teacher / Educator', value: 'Teacher' },
	{ label: 'Student', value: 'Student' },
	{ label: 'Engineer', value: 'Engineer' },
	{ label: 'Software Developer', value: 'Software Developer' },
	{ label: 'Police / Law Enforcement', value: 'Police' },
	{ label: 'Firefighter', value: 'Firefighter' },
	{ label: 'Military Personnel', value: 'Military' },
	{ label: 'Public Transport Worker', value: 'Public Transport Worker' },
	{ label: 'Factory Worker', value: 'Factory Worker' },
	{ label: 'Retail Worker', value: 'Retail Worker' },
	{ label: 'Delivery Personnel', value: 'Delivery' },
	{ label: 'Construction Worker', value: 'Construction' },
	{ label: 'Flight Crew / Airline Staff', value: 'Flight Crew' },
	{ label: 'Journalist / Media Personnel', value: 'Journalist' },
	{ label: 'Government Employee', value: 'Government Employee' },
	{ label: 'Unemployed', value: 'Unemployed' },
	{ label: 'Homemaker', value: 'Homemaker' },
	{ label: 'Farmer', value: 'Farmer' },
	{ label: 'Driver (e.g., Taxi/Truck)', value: 'Driver' }
];
